
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
    private global::Gtk.Frame frame1;

    private global::Gtk.Alignment GtkAlignment;

    private global::Gtk.Fixed fixed1;

    private global::Gtk.ScrolledWindow GtkScrolledWindow;

    private global::Gtk.TextView textview1;

    private global::Gtk.ScrolledWindow GtkScrolledWindow1;

    private global::Gtk.TextView textview2;

    private global::Gtk.Label xlabel;

    private global::Gtk.Label ylabel;

    private global::Gtk.Label zlabel;

    private global::Gtk.TextView xtext;

    private global::Gtk.TextView ytext;

    private global::Gtk.TextView ztext;

    private global::Gtk.Button button1;

    private global::Gtk.Button button4;

    private global::Gtk.Label timertext;

    private global::Gtk.Label label2;

    private global::Gtk.Label label1;

    private global::Gtk.TextView calcprec;

    private global::Gtk.TextView printprec;

    private global::Gtk.CheckButton digitgrp;

    protected virtual void Build ()
    {
        global::Stetic.Gui.Initialize (this);
        // Widget MainWindow
        this.WidthRequest = 745;
        this.HeightRequest = 450;
        this.Name = "MainWindow";
        this.Title = global::Mono.Unix.Catalog.GetString ("GMP Calc");
        this.WindowPosition = ((global::Gtk.WindowPosition)(4));
        this.Resizable = false;
        this.AllowGrow = false;
        this.Gravity = ((global::Gdk.Gravity)(10));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.frame1 = new global::Gtk.Frame ();
        this.frame1.Name = "frame1";
        this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
        // Container child frame1.Gtk.Container+ContainerChild
        this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(12));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.fixed1 = new global::Gtk.Fixed ();
        this.fixed1.Name = "fixed1";
        this.fixed1.HasWindow = false;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
        this.GtkScrolledWindow.Name = "GtkScrolledWindow";
        this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
        this.textview1 = new global::Gtk.TextView ();
        this.textview1.Buffer.Text = "(4 * atan(x / 5) - atan(y / 239)) * 4";
        this.textview1.WidthRequest = 700;
        this.textview1.HeightRequest = 130;
        this.textview1.CanFocus = true;
        this.textview1.Name = "textview1";
        this.textview1.WrapMode = ((global::Gtk.WrapMode)(3));
        this.GtkScrolledWindow.Add (this.textview1);
        this.fixed1.Add (this.GtkScrolledWindow);
        global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow]));
        w2.X = 5;
        w2.Y = 13;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
        this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
        this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
        // Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
        this.textview2 = new global::Gtk.TextView ();
        this.textview2.WidthRequest = 700;
        this.textview2.HeightRequest = 150;
        this.textview2.CanFocus = true;
        this.textview2.Name = "textview2";
        this.textview2.Editable = false;
        this.textview2.WrapMode = ((global::Gtk.WrapMode)(3));
        this.GtkScrolledWindow1.Add (this.textview2);
        this.fixed1.Add (this.GtkScrolledWindow1);
        global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.GtkScrolledWindow1]));
        w4.X = 5;
        w4.Y = 168;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.xlabel = new global::Gtk.Label ();
        this.xlabel.Name = "xlabel";
        this.xlabel.LabelProp = global::Mono.Unix.Catalog.GetString ("x =");
        this.fixed1.Add (this.xlabel);
        global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.xlabel]));
        w5.X = 525;
        w5.Y = 340;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.ylabel = new global::Gtk.Label ();
        this.ylabel.Name = "ylabel";
        this.ylabel.LabelProp = global::Mono.Unix.Catalog.GetString ("y =");
        this.fixed1.Add (this.ylabel);
        global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ylabel]));
        w6.X = 525;
        w6.Y = 370;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.zlabel = new global::Gtk.Label ();
        this.zlabel.Name = "zlabel";
        this.zlabel.LabelProp = global::Mono.Unix.Catalog.GetString ("z =");
        this.fixed1.Add (this.zlabel);
        global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.zlabel]));
        w7.X = 525;
        w7.Y = 400;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.xtext = new global::Gtk.TextView ();
        this.xtext.Buffer.Text = "1";
        this.xtext.WidthRequest = 150;
        this.xtext.HeightRequest = 20;
        this.xtext.CanFocus = true;
        this.xtext.Name = "xtext";
        this.xtext.WrapMode = ((global::Gtk.WrapMode)(3));
        this.fixed1.Add (this.xtext);
        global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.xtext]));
        w8.X = 555;
        w8.Y = 340;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.ytext = new global::Gtk.TextView ();
        this.ytext.Buffer.Text = "1";
        this.ytext.WidthRequest = 150;
        this.ytext.HeightRequest = 20;
        this.ytext.CanFocus = true;
        this.ytext.Name = "ytext";
        this.ytext.WrapMode = ((global::Gtk.WrapMode)(3));
        this.fixed1.Add (this.ytext);
        global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ytext]));
        w9.X = 555;
        w9.Y = 370;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.ztext = new global::Gtk.TextView ();
        this.ztext.Buffer.Text = "1";
        this.ztext.WidthRequest = 150;
        this.ztext.HeightRequest = 20;
        this.ztext.CanFocus = true;
        this.ztext.Name = "ztext";
        this.ztext.WrapMode = ((global::Gtk.WrapMode)(3));
        this.fixed1.Add (this.ztext);
        global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.ztext]));
        w10.X = 555;
        w10.Y = 400;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.button1 = new global::Gtk.Button ();
        this.button1.WidthRequest = 100;
        this.button1.CanFocus = true;
        this.button1.Events = ((global::Gdk.EventMask)(256));
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = global::Mono.Unix.Catalog.GetString ("Clear");
        this.fixed1.Add (this.button1);
        global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button1]));
        w11.X = 354;
        w11.Y = 407;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.button4 = new global::Gtk.Button ();
        this.button4.WidthRequest = 100;
        this.button4.CanFocus = true;
        this.button4.Events = ((global::Gdk.EventMask)(256));
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = global::Mono.Unix.Catalog.GetString ("=");
        this.fixed1.Add (this.button4);
        global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.button4]));
        w12.X = 230;
        w12.Y = 407;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.timertext = new global::Gtk.Label ();
        this.timertext.Name = "timertext";
        this.timertext.LabelProp = global::Mono.Unix.Catalog.GetString ("0 ms");
        this.fixed1.Add (this.timertext);
        global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.timertext]));
        w13.X = 19;
        w13.Y = 414;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.label2 = new global::Gtk.Label ();
        this.label2.Name = "label2";
        this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Print precision:");
        this.fixed1.Add (this.label2);
        global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
        w14.X = 5;
        w14.Y = 370;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.label1 = new global::Gtk.Label ();
        this.label1.Name = "label1";
        this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Calc precision:");
        this.fixed1.Add (this.label1);
        global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
        w15.X = 5;
        w15.Y = 340;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.calcprec = new global::Gtk.TextView ();
        this.calcprec.Buffer.Text = "10005";
        this.calcprec.WidthRequest = 100;
        this.calcprec.HeightRequest = 20;
        this.calcprec.CanFocus = true;
        this.calcprec.Name = "calcprec";
        this.fixed1.Add (this.calcprec);
        global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.calcprec]));
        w16.X = 113;
        w16.Y = 340;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.printprec = new global::Gtk.TextView ();
        this.printprec.Buffer.Text = "10000";
        this.printprec.WidthRequest = 100;
        this.printprec.HeightRequest = 20;
        this.printprec.CanFocus = true;
        this.printprec.Name = "printprec";
        this.fixed1.Add (this.printprec);
        global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.printprec]));
        w17.X = 113;
        w17.Y = 370;
        // Container child fixed1.Gtk.Fixed+FixedChild
        this.digitgrp = new global::Gtk.CheckButton ();
        this.digitgrp.CanFocus = true;
        this.digitgrp.Events = ((global::Gdk.EventMask)(256));
        this.digitgrp.Name = "digitgrp";
        this.digitgrp.Label = global::Mono.Unix.Catalog.GetString ("Digit grouping");
        this.digitgrp.Active = true;
        this.digitgrp.DrawIndicator = true;
        this.digitgrp.UseUnderline = true;
        this.fixed1.Add (this.digitgrp);
        global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.digitgrp]));
        w18.X = 250;
        w18.Y = 340;
        this.GtkAlignment.Add (this.fixed1);
        this.frame1.Add (this.GtkAlignment);
        this.Add (this.frame1);
        if ((this.Child != null)) {
            this.Child.ShowAll ();
        }
        this.DefaultWidth = 800;
        this.DefaultHeight = 450;
        this.Show ();
        this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
        this.button1.Clicked += new global::System.EventHandler (this.clearbuttonclicked);
        this.button4.Clicked += new global::System.EventHandler (this.apress);
        this.digitgrp.Toggled += new global::System.EventHandler (this.digitgrpchanged);
    }
}
